name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  pre-build:
    name: Pre build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v7
    - name: Check code styles
      run: cargo fmt --check
  build-linux:
    name: Build
    uses: ./.github/workflows/build-linux.yml
    needs: pre-build
  build-mac:
    name: Build
    uses: ./.github/workflows/build-mac.yml
    needs: pre-build
